// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbdrrmiwnlumqghjwuyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZHJybWl3bmx1bXFnaGp3dXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjY1MjksImV4cCI6MjA2MDgwMjUyOX0.fuaz25GjHp3BV6WizbFBj1Mh_bTpFuD79I6GkDY77W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);